# Generated by Agent Platform — 2026-05-17T22:22:03.857Z
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
    awscc = { source = "hashicorp/awscc", version = "~> 1.0" }
    time = { source = "hashicorp/time", version = "~> 0.11" }
  }
  backend "s3" {
    bucket         = "my-agents1234-dev-tfstate"
    key            = "my-agents1234/dev/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "my-agents1234-dev-tflock"
    encrypt        = true
  }
}

provider "aws" {
  region = var.region
  default_tags {
    tags = {
    Project = "my-agents1234"
    Environment = "dev"
    ManagedBy = "agentforge"
    Team = "platform"
    }
  }
}

resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = { Name = "my-agents1234-dev-vpc" }
}

resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 10)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags              = { Name = "my-agents1234-dev-private-${count.index}" }
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_ecs_cluster" "main" {
  name = "my-agents1234-dev-cluster"
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

resource "aws_s3_bucket" "skills" {
  bucket = "my-agents1234-dev-skills"
}

resource "aws_s3_bucket_versioning" "skills" {
  bucket = aws_s3_bucket.skills.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_cloudwatch_log_group" "mcp" {
  name              = "/my-agents1234/dev/mcp"
  retention_in_days = 14
}

resource "aws_security_group" "agent" {
  name_prefix = "my-agents1234-dev-agent-"
  vpc_id      = aws_vpc.main.id
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_iam_role" "ecs_execution" {
  name = "my-agents1234-dev-ecs-execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role" "ecs_task" {
  name = "my-agents1234-dev-ecs-task"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role" "agent_task" {
  name = "my-agents1234-dev-agent-task"
  assume_role_policy = aws_iam_role.ecs_task.assume_role_policy
}

resource "aws_iam_role_policy" "agent_s3" {
  name = "skills-read"
  role = aws_iam_role.agent_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["s3:GetObject", "s3:ListBucket"]
      Resource = [aws_s3_bucket.skills.arn, "${aws_s3_bucket.skills.arn}/*"]
    }]
  })
}

resource "aws_iam_role" "lambda_mcp" {
  name = "my-agents1234-dev-lambda-mcp"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_ecs_task_definition" "browser_mcp" {
  family                   = "my-agents1234-browser-mcp"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.ecs_task.arn

  container_definitions = jsonencode([{
    name  = "browser-mcp"
    image = "ghcr.io/example/browser-mcp:latest"
    portMappings = [{ containerPort = 8080, protocol = "tcp" }]
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = aws_cloudwatch_log_group.mcp.name
        "awslogs-region"        = var.region
        "awslogs-stream-prefix" = "browser-mcp"
      }
    }
  }])

  tags = {
    Project = "my-agents1234"
    Environment = "dev"
    ManagedBy = "agentforge"
    Team = "platform"
  }
}
resource "aws_lambda_function" "mcp_c5iqpf2" {
  function_name = "my-agents1234-mcp-c5iqpf2"
  role          = aws_iam_role.lambda_mcp.arn
  package_type  = "Image"
  image_uri     = "jsjns"
  timeout       = 30
  memory_size   = 512

  environment {
    variables = { MCP_PORT = "8080" }
  }

  tags = {
    Project = "my-agents1234"
    Environment = "dev"
    ManagedBy = "agentforge"
    Team = "platform"
  }
}
resource "aws_s3_object" "skill_code_review" {
  bucket  = aws_s3_bucket.skills.id
  key     = "skills/code-review/SKILL.md"
  content = "# Code Review Skill\n\nReview pull requests for security and style."
  etag    = md5("# Code Review Skill\n\nReview pull requests for security and style.")
}
resource "aws_ecs_service" "agent_default_workspace" {
  name            = "my-agents1234-default-workspace"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.agent_default_workspace.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.agent.id]
    assign_public_ip = false
  }

  tags = {
    Project = "my-agents1234"
    Environment = "dev"
    ManagedBy = "agentforge"
    Team = "platform"
  }
}

resource "aws_ecs_task_definition" "agent_default_workspace" {
  family                   = "my-agents1234-default-workspace"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "1024"
  memory                   = "2048"
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.agent_task.arn

  container_definitions = jsonencode([{
    name  = "agent"
    image = "public.ecr.aws/docker/library/node:20-alpine"
    command = ["sh", "-c", "echo Agent space default-workspace ready; sleep infinity"]
    environment = [
      { name = "MCP_REFS", value = "browser-mcp" },
      { name = "SKILL_REFS", value = "code-review" },
      { name = "SKILLS_BUCKET", value = aws_s3_bucket.skills.id }
    ]
  }])

  tags = {
    Project = "my-agents1234"
    Environment = "dev"
    ManagedBy = "agentforge"
    Team = "platform"
  }
}
